import argparse
import json
import logging
import time
from pathlib import Path
from typing import List, Optional

import numpy as np
import tqdm
from endee import Endee

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

DEV_PATH = "https://dev.endee.io/api/v1"


class EndeeIndexing:

    def __init__(self, token: str, base_url: str = DEV_PATH):
        self.vx = Endee(token=token)
        self.vx.set_base_url(base_url)
        self.base_url = base_url
        logger.info("Connected to Endee at %s", base_url)

    def create_index(
        self,
        name: str,
        dimension: int,
        space_type: str = "cosine",
        sparse_model: str = "default",
        precision: str = "float32",
    ):
        result = self.vx.create_index(
            name=name,
            dimension=dimension,
            space_type=space_type,
            sparse_model=sparse_model,
            precision=precision,
        )
        logger.info("Index '%s' created", name)
        return result

    def get_index(self, name: str):
        return self.vx.get_index(name)

    def delete_index(self, name: str):
        result = self.vx.delete_index(name)
        logger.info("Index '%s' deleted", name)
        return result

    @staticmethod
    def _load_dense(base: Path, dataset_name: str):
        """Load dense embeddings via memmap — the full matrix is never in RAM."""
        dense_path     = base / f"{dataset_name}_dense_corpus.npy"
        dense_ids_path = base / f"{dataset_name}_dense_corpus_ids.npy"
        logger.info("Loading dense embeddings from %s", dense_path)
        dense     = np.load(str(dense_path), mmap_mode="r")        # shape (N, dim)
        dense_ids = np.load(str(dense_ids_path), allow_pickle=True)
        n_docs, dim = dense.shape
        logger.info("Dense: %d vectors, dim=%d", n_docs, dim)
        return dense, dense_ids, n_docs, dim

    @staticmethod
    def _load_sparse(base: Path, dataset_name: str, sparse_mode: str):
        """Load sparse flat arrays via memmap; indptr is small so loaded fully."""
        sp_base = base / f"{dataset_name}_sparse_corpus_{sparse_mode}"
        logger.info("Loading sparse embeddings from %s_*.npy", sp_base)
        sp_values  = np.load(str(sp_base) + "_values.npy",      mmap_mode="r")
        sp_indices = np.load(str(sp_base) + "_col_indices.npy",  mmap_mode="r")
        sp_indptr  = np.load(str(sp_base) + "_indptr.npy")       # (N+1,) — small, load fully
        sp_ids     = np.load(str(sp_base) + "_ids.npy",          allow_pickle=True)
        logger.info("Sparse: %d vectors, %d nnz total", len(sp_ids), sp_indptr[-1])
        return sp_values, sp_indices, sp_indptr, sp_ids

    def index_from_npy(
        self,
        index_name: str,
        data_dir: str,
        dataset_name: str,
        output_base: str,
        sparse_mode: str = "bm25",
        batch_size: int = 1000,
        max_retries: int = 15,
    ):
        """
        Index vectors from .npy files generated by embedding_creation_v2.py.

        Expects files under data_dir/dataset_name/:
          <dataset_name>_dense_corpus.npy           — float32 (N, dim)
          <dataset_name>_dense_corpus_ids.npy        — str     (N,)
          <dataset_name>_sparse_corpus_<mode>_values.npy      — float32 (total_nnz,)
          <dataset_name>_sparse_corpus_<mode>_col_indices.npy — int32   (total_nnz,)
          <dataset_name>_sparse_corpus_<mode>_indptr.npy      — int64   (N+1,)
          <dataset_name>_sparse_corpus_<mode>_ids.npy         — str     (N,)
        """
        base = Path(data_dir) / dataset_name

        dense, dense_ids, n_docs, dim                   = self._load_dense(base, dataset_name)
        sp_values, sp_indices, sp_indptr, sp_ids        = self._load_sparse(base, dataset_name, sparse_mode)
        n_sparse = len(sp_ids)

        try:
            index = self.get_index(index_name)
            upsert_times: List[float] = []
            total_inserted = 0
            start_time = time.perf_counter()

            # Iterate over sparse docs (they are the ones with valid sparse vectors).
            # For each sparse doc, advance the dense pointer until the IDs match.
            # sparse_ids is a subset of dense_ids in the same relative order.
            dense_ptr = 0

            for batch_start in tqdm.tqdm(range(0, n_sparse, batch_size), unit="batch"):
                batch_end = min(batch_start + batch_size, n_sparse)

                points = []
                for j in range(batch_start, batch_end):
                    sp_doc_id = str(sp_ids[j])

                    # Advance dense pointer until IDs match
                    while dense_ptr < n_docs and str(dense_ids[dense_ptr]) != sp_doc_id:
                        dense_ptr += 1

                    if dense_ptr >= n_docs:
                        logger.warning("Dense doc not found for sparse doc %s, skipping", sp_doc_id)
                        continue

                    dv = dense[dense_ptr].tolist()
                    dense_ptr += 1

                    s, e = int(sp_indptr[j]), int(sp_indptr[j + 1])
                    raw_vals = sp_values[s:e]
                    raw_idxs = sp_indices[s:e]
                    mask = raw_vals != 0
                    mask = raw_vals != 0

                    points.append({
                        "id": sp_doc_id,
                        "vector": dv,
                        "sparse_indices": raw_idxs[mask].tolist(),
                        "sparse_values":  raw_vals[mask].tolist(),
                        "meta": {"id": sp_doc_id},
                    })

                t0 = time.perf_counter()
                for attempt in range(max_retries):
                    try:
                        index.upsert(points)
                        break
                    except Exception as e:
                        logger.warning("Server busy (attempt %d/%d): %s", attempt + 1, max_retries, e)
                        if attempt < max_retries - 1:
                            time.sleep(1.5)
                        else:
                            raise
                upsert_times.append((time.perf_counter() - t0) * 1000)
                total_inserted += len(points)

            total_time_sec = time.perf_counter() - start_time
            logger.info("Indexing complete: %d vectors in %.2f seconds", total_inserted, total_time_sec)
            self._save_index_performance(output_base, index_name, upsert_times, total_inserted, total_time_sec, batch_size)

        except Exception as e:
            logger.error("Indexing failed: %s", e)
            raise

    def _save_index_performance(
        self,
        output_base: str,
        index_name: str,
        upsert_times_ms: List[float],
        total_inserted: int,
        total_time_sec: float,
        batch_size: int,
    ):
        out_dir = Path(output_base)
        out_dir.mkdir(parents=True, exist_ok=True)
        out_file = out_dir / f"{index_name}.json"

        t = np.array(upsert_times_ms)
        performance = {
            "index_name":        index_name,
            "total_vectors":     total_inserted,
            "total_batches":     len(upsert_times_ms),
            "batch_size":        batch_size,
            "total_time_sec":    round(total_time_sec, 3),
            "upsert_latency_ms": {
                "min":  round(float(t.min()),                  3),
                "p50":  round(float(np.percentile(t, 50)),     3),
                "p95":  round(float(np.percentile(t, 95)),     3),
                "p99":  round(float(np.percentile(t, 99)),     3),
                "max":  round(float(t.max()),                  3),
                "mean": round(float(t.mean()),                 3),
            },
        }

        with open(out_file, "w") as f:
            json.dump(performance, f, indent=2)
        logger.info("Performance saved to %s", out_file)


def main():
    parser = argparse.ArgumentParser(description="Index vectors from .npy files into Endee.")
    parser.add_argument("--index-name",    required=True,  help="Name of the Endee index")
    parser.add_argument("--data-dir",      default="data", help="Root data directory (default: data)")
    parser.add_argument("--dataset-name",  required=True,  help="Dataset name (e.g. beir_scifact, beir_quora)")
    parser.add_argument("--sparse-mode",   default="bm25", choices=["bm25","endee_bm25","splade"],
                        help="Sparse embedding type to use (default: bm25)")
    parser.add_argument("--vector-token",  default="12345678", help="Endee API token (default: 12345678)")
    parser.add_argument("--base-url",      default=DEV_PATH, help=f"Endee base URL (default: {DEV_PATH})")
    parser.add_argument("--batch-size",    type=int, default=1000, help="Upsert batch size (default: 1000)")
    parser.add_argument("--create-index",  type=lambda x: x.lower() != "false", default=True,
                        help="Create the index before ingesting (default: true)")
    parser.add_argument("--dimension",     type=int, default=384,    help="Dense vector dimension (default: 384)")
    parser.add_argument("--space-type",    default="cosine",         help="Distance metric (default: cosine)")
    parser.add_argument("--sparse-scoring-model", default="default", help="Sparse scoring model (default: default)")
    parser.add_argument("--precision",     default="float32",        help="Vector precision (default: float32)")
    parser.add_argument("--output-base",   default="result",           help="Base output directory (default: result)")
    args = parser.parse_args()

    ei = EndeeIndexing(token=args.vector_token, base_url=args.base_url)
    if args.create_index:
        ei.create_index(
            name=args.index_name,
            dimension=args.dimension,
            space_type=args.space_type,
            sparse_model=args.sparse_scoring_model,
            precision=args.precision,
        )
    ei.index_from_npy(
        index_name=args.index_name,
        data_dir=args.data_dir,
        dataset_name=args.dataset_name,
        output_base=args.output_base,
        sparse_mode=args.sparse_mode,
        batch_size=args.batch_size,
    )


if __name__ == "__main__":
    main()
